# Generated by Django 2.0.5 on 2018-07-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='lasted_updated',
            new_name='last_updated',
        ),
    ]
